### ISSUE TITLE
Home page issues #1

### ISSUE THREAD

**Issue by sattastudd** [sattastudd/KhanaShana#7]
1. Differentiation between restaurants and dishes search result.
2. A modal with all the localities in the city should appear after clicking on search by location.
3. The default drop down should appear when nothing is typed in search field and should disappear when any word is typed.
4. Only 10 localities should be visible on home page

**Comment by grvtiwari** [comment]
1. Heading is bold and no background-color in on hover.
2. A modal with all localities is shown on clicking on dropdown menu item saying 'Search All Locations'.
3. When a user has typed, results will be shown according to content typed.
4. Only 10 localities are shown on homepage, it would depend on a flag and last modified date.

Issues fixed in (commit).[https://github.com/sattastudd/KhanaShana/commit/f1b3119fef8fc92f062d3a2c478d7f72cfdda43f]

**Comment by sattastudd** [comment]
*slow claps* Bravo
